MozillaReality/webxr-ios-js

- src/extensions/XRFaceMesh.js
- src/extensions/XRMesh.js
Should be more tollerant to missing data, and do less allocations
> cleaned up how meshes are updated

- src/arkit/ARKitWrapper.js
This message is used in the timing of Metal rendering
> Post onUpdate at the end of finishedRender

- src/webxr.js
Following #28 
This PR updates `src/webxr.js` to follow the latest WebXR API core spec. (I make other PRs for hit-test, anchor, and light estimation APIs.)
The changes in this PR are
- Override `WebXRPolyfill.prototype._patchNavigatorXR`, instead of `WebXRPolyfill.prototype._patchRequestDevice`, to let the polyfill create our device
- Remove `XRFrameOfReference` because no longer exists
- Remove `getTransformTo()` because no longer exists. We should use `XRFrame.getPose()` instead
- Override `XRFrame.getPose()` because the official polyfill doesn't support yet ([The issue has been opened in the official webxr-polyfill repo](https://github.com/immersive-web/webxr-polyfill/issues/92))
> Update src/webxr.js to follow the latest WebXR API core spec

- src/webxr.js
Following #30 
This PR updates anchor API based on https://github.com/immersive-web/anchors/blob/master/explainer.md See the note comment in the code for the detail about workaround.
> Update anchor API

- examples/ar_simplest/index.html
Following #31 #32 #33 #34 
This PR updates `ar_simplest` example. I just tested to check it likely keeps working. I'm happy if you check in your side, too.
This is the first PR updating the examples. If looking ok end it's merged, I'll send other PRs updating other examples one by one.
Don't forget to update `dist` and edit the path in `xrshim.js` if you test in your side.
The changes
- Load shim instead of directly loading the entire polyfill
- Follow the latest WebXR API
- Clean up; formatting, ES6 style, and so on
> Update ar_simlest example

- examples/ar_anchors/index.html
This PR updates ar_anchors example. The changes and the comment are same as #35
> Update ar_anchors example

- examples/boombox/index.html
This PR updates boombox example. The changes and the comment are same as #35
> Update boombox example

- examples/face_tracking/index.html
This PR updates face_tracking example. The changes and the comment is same as #35
Note that as I informed you on email I couldn't test face tracking example in my side because the iPad I borrowed seems too old. I'm happy if you test in your side.
> Update face_tracking example

- examples/hit_test/index.html
This PR updates hit_test example. The changes and the comment is same as #35
> Update hit_test example

- examples/image_detection/index.html
This PR updates image_detection example. The changes and the comment are same as #35
> Update image_detection example

- examples/light/index.html
This PR updates light example. The changes and the comment are same as #35
> Update light example

- examples/peoples/index.html
This PR updates people example. The changes and the comment are same as #35
> Update people example

- examples/reticle/index.html
This PR updates reticle example. The changes and the comment are same as #35
> Update reticle example

- examples/sensing/index.html
This PR updates sensing example. The changes and the comment are same as #35
> Update sensing example

- src/webxr.js
From #48
This PR includes
- Consist formatting
- Remove/Update out date comments
- Add comments
> Clean up web src/webxr.js

- src/arkit/ARKitWatcher.js
From #48.
This PR includes
- Consistent formatting
> Clean up ARKitWatcher.js

- src/arkit/ARKitWrapper.js
From #48 
This PR includes
- Consistent formatting
- Remove out date comments
- Add comments
- Remove unused variables and functions
- More structured code
Let me know if this PR is too huge.
> Clean up ARKitWrapper.js

- xrshim.js
Following #60. I found duplicated lines and unclear comment. This PR resolves them.
> Some Clean up for shim

- examples/light/index.html
This is a follow up PR to #84 and updates Light example to follow the newest WebXR spec.
> Update light example to follow the newest WebXR spec

- examples/reticle/index.html
This PR is a follow up PR to #84 and updates Reticle example to follow the newest WebXR spec.
> Update Reticle example to follow the newest spec

- examples/hit_test/index.html
- examples/peoples/index.html
This PR is a follow up PR to #84 and updates People example to follow the newest WebXR spec.
> Update People example to follow the newest WebXR spec

- examples/sensing/index.html
This is a follow up PR to #84 and updates World sensing example to follow the newest WebXR spec.
> Update WorldSensing example to follow the newest WebXR spec

- examples/ar_simplest/index.html
This PR cleans up Simplest example for the consistent coding style with other updates exmples.
> Clean up Simplest example

- examples/boombox/index.html
Similar to #91, this PR cleans up Boombox example.
> Clean up Boombox example

- examples/ar_anchors/index.html
This PR updates Anchor example to follow the newest WebXR API. (Not newest Anchor API yet, see #93)
> Update Anchor example to follow the newest WebXR API

- src/arkit/ARKitDevice.js
> Disable background image in immersive mode

- examples/face_tracking/index.html
As I mentioned before, my iPad doesn't seem to support face tracking so I'm happy if someone tests in your side.
> Clean up Face tracking example

- src/arkit/ARKitDevice.js
- src/webxr.js
Tested on https://storage.googleapis.com/chromium-webxr-test/r757560/proposals/index.html
(The example doesn't work as is due to #81 so you need to download and comment out addEventListener line causing the error if you want to test in your side.)
Note: [Fullscreen API integration](https://immersive-web.github.io/dom-overlays/#fullscreen-api-integration) is not supported yet. I want to add it later.
> Add DomOverlay API support
